language: objective-c
xcode_project: TestCI.xcodeproj
xcode_scheme: TestCI
notifications:
  email: false
script: xctool -project TestCI.xcodeproj -scheme TestCI build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
